### ISSUE TITLE
Доработать ETL для записи в ES данных жанров (5 s.p.)

### ISSUE THREAD

**Issue by zhovtanovskaya** [zhovtanovskaya/new_admin_panel_sprint_3#2]
Добавить новый ETL пайплайн, в котором создается и заполняется индекс genres из всех жанров, которые есть в фильмах. Плоский индекс без денормализованных данных. Хранить ссылки на фильмы не нужно.

Оценка: 5

Перенесено из репозитория [AsyncAPI Sprint 1](https://github.com/zhovtanovskaya/Async_API_sprint_1/issues/6).

**Comment by swats-the-floran** [comment]
возможно придётся изменить настройки для работы с твоим проектом.
